export { default as About } from './about/about.jsx'
export { default as Contact } from './contact/contact';
export { default as Header } from './header/header';
export { default as NavbarMobile } from './navigation/navbar-mobile';
export { default as Projects } from './projects/projects';
export { default as Skills } from './skills/skills';
export { default as CTA } from './cta/cta';
export { default as Footer } from './footer/footer';
export { default as Background } from './background/background';
